spring:
  security:
    user:
      name: admin
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 11111
    driver-class-name: com.mysql.jdbc.Driver